# 每月26号华山论剑荣誉兑换
华山论剑:
  - name: 钻石
    id: 6857
    exchange_quantity: 100
  - name: 侠士修身录
    id: 6347
    exchange_quantity: 0
  - name: 侠士手记
    id: 6348
    exchange_quantity: 0
  - name: 重出江湖令
    id: 6349
    exchange_quantity: 0
  - name: 斗神符
    id: 3090
    exchange_quantity: 0

乐斗:
  disable_boss_uin: # 禁止乐斗好友BOSS
    # - "161" # 斗神幻象
    # - "33" # 金鹅毛王
    # - "16" # 乐斗程管
    # - "12" # 俊猴王
    # - "11" # 月敏妹妹
    # - "9" # 乐斗剑君
    # - "7" # 乐斗菜菜
    # - "151" # 新手小王子

  贡献药水: 4 # 每天使用次数

  体力药水: true # 开启自动使用
  # 体力药水: false # 取消自动使用

  情师徒拜: true # 乐斗
  # 情师徒拜: false # 不乐斗

# 巅峰之战进行中: 0 # 随机加入
# 巅峰之战进行中: 1 # 报名南派
巅峰之战进行中: 2 # 报名北派

# 选择矿洞副本
矿洞: floor=1&mode=1 # 第一层（简单）
# 矿洞: floor=1&mode=2 # 第一层（普通）
# 矿洞: floor=1&mode=3 # 第一层（困难）
# 矿洞: floor=2&mode=1 # 第二层（简单）
# 矿洞: floor=2&mode=2 # 第二层（普通）
# 矿洞: floor=2&mode=3 # 第二层（困难）
# 矿洞: floor=3&mode=1 # 第三层（简单）
# 矿洞: floor=3&mode=2 # 第三层（普通）
# 矿洞: floor=3&mode=3 # 第三层（困难）
# 矿洞: floor=4&mode=1 # 第四层（简单）
# 矿洞: floor=4&mode=2 # 第四层（普通）
# 矿洞: floor=4&mode=3 # 第四层（困难）
# 矿洞: floor=5&mode=1 # 第五层（简单）
# 矿洞: floor=5&mode=2 # 第五层（普通）
# 矿洞: floor=5&mode=3 # 第五层（困难）

# 是否每月1~25号兑换10个河图洛书
# 竞技场: true # 兑换
竞技场: false # 不兑换

# 选择十二宫场景
十二宫: 1000 # 白羊宫
# 十二宫: 1001 # 金牛宫
# 十二宫: 1002 # 双子宫
# 十二宫: 1003 # 巨蟹宫
# 十二宫: 1004 # 狮子宫
# 十二宫: 1005 # 处女宫
# 十二宫: 1006 # 天秤宫
# 十二宫: 1007 # 天蝎宫
# 十二宫: 1008 # 射手宫
# 十二宫: 1009 # 摩羯宫
# 十二宫: 1010 # 水瓶宫
# 十二宫: 1011 # 双鱼宫

# 每个BOSS乐斗一次，因为取消自动使用活力药水，所以最多乐斗前5个BOSS
历练:
  - 6114 # 摩云山 韦小宝碎片
  - 6134 # 洞庭湖 扫地僧碎片
  - 6154 # 苍莽山 鹤笔翁碎片
  - 6034 # 林松郊外 令狐冲碎片
  - 6054 # 林松城 丁春秋碎片
  - 6074 # 东海龙宫 丘处机碎片
  - 6094 # 踏云镇 小龙女碎片
  - 6174 # 玉龙湿地 韦一笑碎片
  - 6194 # 玉龙雪山 赵敏碎片

# 选择拦截镖师
镖行天下: "" # 不限定镖师
# 镖行天下: 蔡八斗
# 镖行天下: 吕青橙
# 镖行天下: 温良恭

# 选择幻境场景
幻境: 1 # 乐斗村
# 幻境: 2 # 林松郊外
# 幻境: 3 # 林松城
# 幻境: 4 # 东海龙宫
# 幻境: 5 # 踏云镇
# 幻境: 6 # 摩云山
# 幻境: 7 # 洞庭湖
# 幻境: 8 # 苍莽山
# 幻境: 9 # 玉龙湿地
# 幻境: 10 # 玉龙雪山
# 幻境: 11 # 狂沙台地
# 幻境: 12 # 回声遗迹
# 幻境: 13 # 悲叹山丘
# 幻境: 14 # 黄沙漩涡
# 幻境: 15 # 炎之洞窟
# 幻境: 16 # 程管小镇
# 幻境: 17 # 花果山
# 幻境: 18 # 藏剑山庄
# 幻境: 19 # 桃花剑冢
# 幻境: 20 # 鹅王的试炼

门派:
  # 门派高香: true # 每天门派邀请赛兑换门派高香*1
  门派高香: false # 不兑换

  # 门派战书: true # 每天门派邀请赛兑换门派战书*1
  门派战书: false # 不兑换

# 周一门派邀请赛商店兑换
门派邀请赛:
  - name: 炼气石
    id: 1246
    exchange_quantity: 20
  - name: 门派强化书
    id: 1247
    exchange_quantity: 0
  - name: 门派高香
    id: 1248
    exchange_quantity: 0
  - name: 门派战书
    id: 1249
    exchange_quantity: 0
  - name: 门派引荐书
    id: 1250
    exchange_quantity: 0

# 周四会武商店兑换
会武:
  - name: 真黄金卷轴
    id: 1263
    exchange_quantity: 20
  - name: 修为丹
    id: 1264
    exchange_quantity: 0
  - name: 试炼书
    id: 1265
    exchange_quantity: 3

# 周四消耗梦幻机票完成未去过目的地
梦想之旅: 6 # 最多消耗的梦幻机票数量，如果低于未去过目的地数量则不会消耗

问鼎天下:
  region: 1 # 攻占东海
  # region: 2 # 攻占南荒
  # region: 3 # 攻占西泽
  # region: 4 # 攻占北寒

  # 每天总次数5（3次免费+2次付费）
  # 积分最大化是打4次1级失败+打1次3级成功：30*4+150=270
  level1_occupy_count: 2 # 攻占1级资源点次数，最多4次，3级资源点必攻占一次

  # 傲龙づ族℃：96690
  # 神阁☆圣域：82494
  淘汰赛: 96690 # 周六助威
  排名赛: 96690 # 周日助威

# 选择交易及兑换物品
# 物品支持全字、部分名称及正则匹配（注意使用 \ 转义字符）
帮派商会:
  交易会所:
    - 体力 # 匹配真体力、大体力、小体力等含有体力的物品
    - 经验 # 匹配经验药水、经验木筒等含有经验的物品
    # - 悟性丹\*20 # 匹配悟性丹*20
    # - 百炼钢 # 匹配百炼钢
    # - 凤凰羽毛 # 匹配凤凰羽毛
    # - 奔流气息
    # - 神来拳套
    # - 黄金卷轴
    # - 投掷武器符文石
  兑换商店:
    # - 破坏·银光V碎片 # 武器暴击伤害50.0%，全武器伤害15，该回合伤害提高20.0%
    # - 破坏·闪光V碎片 # 武器暴击伤害50.0%，全武器伤害15，该回合异性伤害35%
    # - 破坏·亮光V碎片 # 武器暴击伤害50.0%，全武器伤害15，降低对方佣兵反弹比例50.0%
    # - 破坏·暴风V碎片 # 武器暴击伤害50.0%，全武器伤害15，忽略装死100.0%
    # - 破坏·狂风V碎片 # 武器暴击伤害50.0%，全武器伤害15，无视格挡100.0%
    # - 破坏·霸风V碎片 # 武器暴击伤害50.0%，全武器伤害15，忽略对方反弹100.0%
    # - 破坏·流风V碎片 # 武器暴击伤害50.0%，全武器伤害15，忽略对方反击100.0%
    # - 破坏·锦月V碎片 # 武器暴击伤害50.0%，全武器伤害15，额外增加速度百分比的伤害50.0%
    # - 破坏·灵月V碎片 # 武器暴击伤害50.0%，全武器伤害15，额外增加力量百分比的伤害100.0%
    # - 破坏·清月V碎片 # 武器暴击伤害50.0%，全武器伤害15，额外增加敏捷百分比的伤害200.0%
    # - 破坏·雪月V碎片 # 武器暴击伤害50.0%，全武器伤害15，额外增加当前生命值百分比的伤害5.0%
    # - 破坏·幽月V碎片 # 武器暴击伤害50.0%，全武器伤害15，额外增加当前等级百分比的伤害300.0%
    # - 闪耀·银光V碎片 # 武器伤害70，全武器伤害15，该回合伤害提高20.0%
    # - 闪耀·闪光V碎片 # 武器伤害70，全武器伤害15，该回合异性伤害35%
    # - 闪耀·亮光V碎片 # 武器伤害70，全武器伤害15，降低对方佣兵反弹比例50.0%
    # - 闪耀·暴风V碎片 # 武器伤害70，全武器伤害15，忽略装死100.0%
    # - 闪耀·狂风V碎片 # 武器伤害70，全武器伤害15，无视格挡100.0%
    # - 闪耀·霸风V碎片 # 武器伤害70，全武器伤害15，忽略对方反弹100.0%
    # - 闪耀·流风V碎片 # 武器伤害70，全武器伤害15，忽略对方反击100.0%
    # - 闪耀·锦月V碎片 # 武器伤害70，全武器伤害15，额外增加速度百分比的伤害50.0%
    # - 闪耀·灵月V碎片 # 武器伤害70，全武器伤害15，额外增加力量百分比的伤害100.0%
    # - 闪耀·清月V碎片 # 武器伤害70，全武器伤害15，额外增加敏捷百分比的伤害200.0%
    # - 闪耀·雪月V碎片 # 武器伤害70，全武器伤害15，额外增加当前生命值百分比的伤害5.0%
    # - 闪耀·幽月V碎片 # 武器伤害70，全武器伤害15，额外增加当前等级百分比的伤害300.0%
    # - 泯灭·焱炎V碎片 # 该武器穿透20.0%，全武器减免15，禁止对手触发吸血的回合数3
    # - 泯灭·异炎V碎片 # 该武器穿透20.0%，全武器减免15，禁止对手触发暴击的回合数3
    # - 泯灭·黑炎V碎片 # 该武器穿透20.0%，全武器减免15，禁止对手触发门派技能的回合数3
    # - 泯灭·苍玉V碎片 # 该武器穿透20.0%，全武器减免15，忽略对手的回合数2
    # - 泯灭·碧玉V碎片 # 该武器穿透20.0%，全武器减免15，忽略对手空手攻击的回合数2
    # - 泯灭·墨玉V碎片 # 该武器穿透20.0%，全武器减免15，忽略对手技能攻击的回合数2
    # - 泯灭·紫晶V碎片 # 该武器穿透20.0%，全武器减免15，连续攻击的概率100.0%
    # - 泯灭·烟晶V碎片 # 该武器穿透20.0%，全武器减免15，闪避反击的概率100.0%
    # - 洞悉·焱炎V碎片 # 武器命中率30.0%，全武器减免15，禁止对手触发吸血的回合数3
    # - 洞悉·异炎V碎片 # 武器命中率30.0%，全武器减免15，禁止对手触发暴击的回合数3
    # - 洞悉·黑炎V碎片 # 武器命中率30.0%，全武器减免15，禁止对手触发门派技能的回合数3
    # - 洞悉·苍玉V碎片 # 武器命中率30.0%，全武器减免15，忽略对手的回合数2
    # - 洞悉·碧玉V碎片 # 武器命中率30.0%，全武器减免15，忽略对手空手攻击的回合数2
    # - 洞悉·墨玉V碎片 # 武器命中率30.0%，全武器减免15，忽略对手技能攻击的回合数2
    # - 洞悉·紫晶V碎片 # 武器命中率30.0%，全武器减免15，连续攻击的概率100.0%
    # - 洞悉·烟晶V碎片 # 武器命中率30.0%，全武器减免15，闪避反击的概率100.0%
    # - 终结·焱炎V碎片 # 该武器抗韧性30.0%，全武器减免15，禁止对手触发吸血的回合数3
    # - 终结·异炎V碎片 # 该武器抗韧性30.0%，全武器减免15，禁止对手触发暴击的回合数3
    # - 终结·黑炎V碎片 # 该武器抗韧性30.0%，全武器减免15，禁止对手触发门派技能的回合数3
    # - 终结·苍玉V碎片 # 该武器抗韧性30.0%，全武器减免15，忽略对手的回合数2
    # - 终结·碧玉V碎片 # 该武器抗韧性30.0%，全武器减免15，忽略对手空手攻击的回合数2
    # - 终结·墨玉V碎片 # 该武器抗韧性30.0%，全武器减免15，忽略对手技能攻击的回合数2
    # - 终结·紫晶V碎片 # 该武器抗韧性30.0%，全武器减免15，连续攻击的概率100.0%
    # - 终结·烟晶V碎片 # 该武器抗韧性30.0%，全武器减免15，闪避反击的概率100.0%
    # - 神佑·落星V碎片 # 手持武器减伤30.0%，生命值40，必中
    # - 神佑·怒意V碎片 # 手持武器减伤30.0%，生命值40，必暴击
    # - 神佑·赤焰V碎片 # 手持武器减伤30.0%，生命值40，100%附带吸血效果50%
    # - 守护·落星V碎片 # 该武器抗穿透20.0%，生命值40，必中
    # - 守护·怒意V碎片 # 该武器抗穿透20.0%，生命值40，必暴击
    # - 守护·赤焰V碎片 # 该武器抗穿透20.0%，生命值40，100%附带吸血效果50%
    # - 坚韧·落星V碎片 # 该武器韧性30.0%，生命值40，必中
    # - 坚韧·怒意V碎片 # 该武器韧性30.0%，生命值40，必暴击
    # - 坚韧·赤焰V碎片 # 该武器韧性30.0%，生命值40，100%附带吸血效果50%

# 选择报名赛场
武林盟主: 1 # 黄金赛场 要求最低战力2000
# 武林盟主: 2 # 白银赛场 要求最低战力1000
# 武林盟主: 3 # 青铜赛场 要求最低战力200

# 黑市商人物品交换配置
# 点击 "与TA交换"，按照 "消耗xx换取xx" 格式填入
侠士客栈:
  # - 消耗斗灵石-空*66换取V级万能碎片*1
  # - 消耗斗神符*1换取淬火结晶*1
  # - 消耗门派强化书*2换取斗灵石-空*5
  # - 消耗还魂丹*30换取百炼钢*1
  # - 消耗挑战书*2换取玄铁令*1
  # - 消耗黄金卷轴*3换取斗神符*1
  # - 消耗无字天书*1换取易经八卦*1

乐斗黄历: 0 # 斗神塔双倍时自动挑战次数（次数耗尽或到不了顶层结束）

深渊之潮:
  深渊秘境:
    # 选择挑战副本id
    id: 1 # 崎岖斗界
    # id: 2 # 魂渡桥
    # id: 3 # 须臾之河
    # id: 4 # 曲镜空洞
    # id: 5 # 光影迷界
    # id: 6 # 吞厄源头
    # id: 7 # 渊秘祭坛
    # id: 8 # 古帝遗迹
    exchange_count: 0 # 第一、二轮兑换副本次数
  许愿帮铺: # 每月26号兑换
    - name: 气魄之书
      id: 5
      exchange_quantity: 0
    - name: 力魄之书
      id: 6
      exchange_quantity: 0
    - name: 精魄之书
      id: 7
      exchange_quantity: 0
    - name: 英魄之书
      id: 8
      exchange_quantity: 0
    - name: 中枢之书
      id: 9
      exchange_quantity: 0
    - name: 天冲之书
      id: 10
      exchange_quantity: 0
    - name: 灵慧之书
      id: 11
      exchange_quantity: 0
    - name: 佣兵天赋丹
      id: 12
      exchange_quantity: 0
    - name: 许愿卡
      id: 13
      exchange_quantity: 0
    - name: 五星许愿卡碎片
      id: 14
      exchange_quantity: 0
    - name: 豆油队长碎片
      id: 15
      exchange_quantity: 0
    - name: 定海制作书
      id: 16
      exchange_quantity: 1

侠客岛:
  侠客行: # 接受有以下奖励的任务，最多免费刷新4次
    - 侠士修身录*2
    # - 侠士修身录*1
    - 侠士手记*2
    # - 侠士手记*1
    # - 秘传菜谱*2
    # - 秘传菜谱*1
    - 鉴宝真炎*2
    # - 鉴宝真炎*1
    - 太玄经*2
    - 太玄经*1
    - 玄铁令*2
    - 玄铁令*1

时空遗迹:
  异兽洞窟: # 依次优先扫荡否则挑战
    - 5 # 异兽母巢
    - 4 # 异兽元帅
    - 3 # 异兽将领
    - 2 # 异兽战士
    - 1 # 异兽幼崽
  遗迹商店:
    1: # 特惠区
      - name: 日引石
        id: 1
        exchange_quantity: 100
      - name: 月引石
        id: 2
        exchange_quantity: 100
      - name: 星引石
        id: 3
        exchange_quantity: 100
      - name: 舆图
        id: 4
        exchange_quantity: 40
    2: # 售卖区
      - name: 日引石
        id: 5
        exchange_quantity: 50
      - name: 月引石
        id: 6
        exchange_quantity: 50
      - name: 星引石
        id: 7
        exchange_quantity: 50
      - name: 舆图
        id: 8
        exchange_quantity: 20

龙凰之境:
  龙凰论武:
    zone: 1 # 报名龙渊赛区
    # zone: 2 # 报名凰极赛区
    challenge_count: 1 # 第一、二轮随机挑战玩家次数
  龙凰云集: # 每月27号兑换
    - name: 论武券
      id: 1
      exchange_quantity: 0
    - name: 龙玉
      id: 2
      exchange_quantity: 0
    - name: 凰髓
      id: 3
      exchange_quantity: 0
    - name: 凰火
      id: 4
      exchange_quantity: 0

# 帮派守护神供奉，每个物品最多供奉5次
我的帮派:
  - 3043 # 被动经验药水
  - 3014 # 经验药水
  - 3001 # 小体力
  - 3003 # 大体力
  - 3028 # 神来拳套
  - 3074 # 追魂锁链
  - 3089 # 还魂丹
  - 3100 # 还童卷轴
  - 3871 # 百炼钢
  - 5391 # 佣兵天赋丹

# 物品名称包含某个字符时会被使用
背包:
  - 盒 # 匹配仙侠盲盒、周年壕气礼盒...
  - 包 # 匹配贡献小笼包、贡献叉烧包...
  - 箱 # 匹配资源补给箱、魂珠碎片宝箱...
  - 锦囊 # 匹配惊喜锦囊、武神坛银锦囊...
  - 阅历 # 匹配阅历卷宗、阅历羊皮卷...
  - 信物 # 匹配蔡八斗的信物、吕青橙的信物...
  - 勋章 # 匹配巅峰之战一等勋章、巅峰之战二等勋章...
  - 大力丸 # 只匹配大力丸、大力丸(赠)
  - 活血散 # 只匹配活血散、活血散(赠)
  - 迅捷珠 # 只匹配迅捷珠、迅捷珠(赠)
  - 风之息 # 只匹配风之息、风之息(赠)
  - 神来拳套(赠) # 只匹配神来拳套(赠)

# 神匠坊选择符石分解，默认 I类
神匠坊:
  - 6161 # 破坏·幽月I
  - 6160 # 闪耀·银光I
  - 6159 # 终结·焱炎I
  - 6158 # 洞悉·紫晶I
  # - 6157 # 破坏·流风II
  # - 6156 # 闪耀·流风II
  # - 6155 # 破坏·幽月II
  # - 6154 # 闪耀·幽月II
  # - 6153 # 破坏·银光II
  # - 6152 # 闪耀·银光II
  # - 6151 # 洞悉·焱炎II
  # - 6150 # 洞悉·焱炎II
  # - 6149 # 终结·苍玉II
  # - 6148 # 洞悉·苍玉II
  # - 6147 # 终结·紫晶II
  # - 6146 # 洞悉·紫晶II
  # - 6145 # 破坏·暴风III
  # - 6144 # 闪耀·暴风III
  # - 6143 # 破坏·狂风III
  # - 6142 # 闪耀·狂风III
  # - 6141 # 破坏·霸风III
  # - 6140 # 闪耀·霸风III
  # - 6139 # 破坏·流风III
  # - 6138 # 闪耀·流风III
  # - 6137 # 破坏·灵月III
  # - 6136 # 闪耀·灵月III
  # - 6135 # 破坏·清月III
  # - 6134 # 闪耀·清月III
  # - 6133 # 破坏·锦月III
  # - 6132 # 闪耀·锦月III
  # - 6131 # 破坏·雪月III
  # - 6130 # 闪耀·雪月III
  # - 6129 # 破坏·幽月III
  # - 6128 # 闪耀·幽月III
  # - 6127 # 破坏·银光III
  # - 6126 # 闪耀·银光III
  # - 6125 # 终结·异炎III
  # - 6124 # 洞悉·异炎III
  # - 6123 # 终结·焱炎III
  # - 6122 # 洞悉·焱炎III
  # - 6121 # 终结·烟晶III
  # - 6120 # 洞悉·烟晶III
  # - 6119 # 终结·紫晶III
  # - 6118 # 洞悉·紫晶III

# 每天出现指定字符时献酒
客栈同福:
  - 王重阳碎片
  - 王处一碎片

# 将一个福卡分享给小号QQ，默认不分享
生肖福卡: 

节日福利: # 活动期间3倍奖励
  历练: true # 每天反向乐斗BOSS
  # 历练: false # 取消乐斗BOSS

  斗神塔: 0 # 周四自动挑战次数（次数耗尽或到不了顶层结束）

金秋福利: # 活动期间3倍奖励
  历练: true # 每天反向乐斗BOSS
  # 历练: false # 取消乐斗BOSS

  斗神塔: 0 # 周四自动挑战次数（次数耗尽或到不了顶层结束）

# 选择周四兑换的物品
# 登录商店: 1221 # 中体力*1
# 登录商店: 1222 # 真体力*1
登录商店: 1223 # 黄金卷轴*1
# 登录商店: 1224 # 孙子兵法*1
# 登录商店: 1225 # 武穆遗书*1
# 登录商店: 1226 # 神秘精华*1
# 登录商店: 1227 # 神兵原石*1
# 登录商店: 1228 # 软猥金丝*1
# 登录商店: 1229 # 凤凰羽毛*1
# 登录商店: 1230 # 潜能果实*1
# 登录商店: 1231 # 上古玉髓*1
# 登录商店: 1232 # 奔流气息*1

# 选择截止日前一天兑换的物品
企鹅吉利兑:
  - name: V级万能碎片
    id: 5
    exchange_quantity: 25
  - name: 熔炼乌金
    id: 6
    exchange_quantity: 100
  - name: 玄铁令
    id: 7
    exchange_quantity: 20
  - name: 挑战书
    id: 8
    exchange_quantity: 30

# 周四指定好友赠送一个同心结
爱的同心结:
  # - QQ1
  # - QQ2

# 周四领取选择奖励
# 乐斗儿童节: type=1&sub_type=0 # 神兵
# 乐斗儿童节: type=1&sub_type=1 # 神铠
# 乐斗儿童节: type=1&sub_type=2 # 神羽
# 乐斗儿童节: type=1&sub_type=3 # 神兽
# 乐斗儿童节: type=1&sub_type=4 # 神饰
# 乐斗儿童节: type=1&sub_type=5 # 神履
# 乐斗儿童节: type=2&sub_type=0 # 坚韧不拔
# 乐斗儿童节: type=2&sub_type=1 # 嗜血如命
乐斗儿童节: type=2&sub_type=2 # 坚定不移
# 乐斗儿童节: type=2&sub_type=3 # 生存本能
# 乐斗儿童节: type=2&sub_type=4 # 横扫千军
# 乐斗儿童节: type=2&sub_type=5 # 三魂之力
# 乐斗儿童节: type=2&sub_type=6 # 四魂天功
# 乐斗儿童节: type=2&sub_type=7 # 炙血战魂
# 乐斗儿童节: type=2&sub_type=8 # 百战之躯
# 乐斗儿童节: type=2&sub_type=9 # 攻无不克
# 乐斗儿童节: type=3&sub_type=0 # 投掷武器专精
# 乐斗儿童节: type=3&sub_type=1 # 小型武器专精
# 乐斗儿童节: type=3&sub_type=2 # 中型武器专精
# 乐斗儿童节: type=3&sub_type=3 # 大型武器专精
# 乐斗儿童节: type=4&sub_type=1 # 强化

# 周四领取选择奖励
# 乐斗开学季: type=1&sub_type=0 # 神兵
# 乐斗开学季: type=1&sub_type=1 # 神铠
# 乐斗开学季: type=1&sub_type=2 # 神羽
# 乐斗开学季: type=1&sub_type=3 # 神兽
# 乐斗开学季: type=1&sub_type=4 # 神饰
# 乐斗开学季: type=1&sub_type=5 # 神履
# 乐斗开学季: type=2&sub_type=0 # 坚韧不拔
# 乐斗开学季: type=2&sub_type=1 # 嗜血如命
乐斗开学季: type=2&sub_type=2 # 坚定不移
# 乐斗开学季: type=2&sub_type=3 # 生存本能
# 乐斗开学季: type=2&sub_type=4 # 横扫千军
# 乐斗开学季: type=2&sub_type=5 # 三魂之力
# 乐斗开学季: type=2&sub_type=6 # 四魂天功
# 乐斗开学季: type=2&sub_type=7 # 炙血战魂
# 乐斗开学季: type=2&sub_type=8 # 百战之躯
# 乐斗开学季: type=2&sub_type=9 # 攻无不克
# 乐斗开学季: type=3&sub_type=0 # 投掷武器专精
# 乐斗开学季: type=3&sub_type=1 # 小型武器专精
# 乐斗开学季: type=3&sub_type=2 # 中型武器专精
# 乐斗开学季: type=3&sub_type=3 # 大型武器专精
# 乐斗开学季: type=4&sub_type=1 # 强化
