# 所有账号共享的任务配置
# TASK_CONFIG优先级：账号配置 > 全局配置
# 任务配置名称必须与账号配置文件中的任务注册一致


TASK_CONFIG: 
  问鼎天下:
    # 傲龙づ族℃：96690
    # 神阁☆圣域：82494
    淘汰赛: 96690 # 周六助威
    排名赛: 96690 # 周日助威

  微信兑换: 251001 # 周四兑换

  时空遗迹:
    八卦迷阵: 坤兑巽坎 # 八卦顺序
